spring:
  application:
    name: spring-eureka-server

server:
  port: 8761

#Eureka Server Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false


